### ISSUE TITLE
[Bug] Not working [full stop]

### ISSUE THREAD

**Issue by JennyWat** [TheMisterFish/Fabric_OfflinePlayersReworked#29]
![image_2024-09-16_214807079](https://github.com/user-attachments/assets/39c64236-9583-4141-bc5c-bc56461050dd)

Don't understand issue. Mod is installed on both
version : 1.21

**Comment by TheMisterFish** [comment]
Sorry for the late response, could you add some more information? What are the steps to reproduce this bug & is there any information in the server logs?

**Comment by TheMisterFish** [comment]
I think I see the mistake, I put in the incorrect URL in the description. 
@JennyWat could you make a new bug report on [TwinSessions](https://github.com/TheMisterFish/Fabric_TwinSession/issues) if this is still a occurring issue.
