### ISSUE TITLE
[Feature] No more dependencies

### ISSUE THREAD

**Issue by TheMisterFish** [TheMisterFish/Fabric_OfflinePlayersReworked#34]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I see how many dependencies this mod has just because of JsonDB already.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

No dependencies, that would be cool.

**Versions**
- Minecraft: latest

**Comment by TheMisterFish** [comment]
@suerion

Could you test the 1.1.0-test version below?
https://www.mediafire.com/file/4m4bbh42mk2un2p/offlineplayersreworked-1.1.0-test.jar/file

I've removed every dependency :) 

Changelog:
**OfflinePlayers-Reworked 1.1.0 (MC 1.21.1)**

**Update:**

- Removed "Other" dependencies
  
  OfflinePlayersReworked now doesn't work with a (JsonDB) database or MidnightLib. Instead it uses the Minecraft internal storage as well as SimpleConfig which has no dependencies.

**Comment by suerion** [comment]
Need a few minutes ;) then i could give you an answere ;)

**Comment by TheMisterFish** [comment]
I think it might be because of the line above it about the OfflinePlayer joining the game. I'll have a look into that. Thanks for checking it out :) I've tested all functionality myself, but was mostly wondering if it wouldn't break when other mods are added. 

If I can't fix that error log it might be a open bug :(

**Comment by suerion** [comment]
COuld be, that i was tooo fast for resources and then the OFF Player was generated to fast, before the Client has disconnected.

But could also another issue :) 

The mod is nice, and has an interessting feature. now it would be not that problem. My Dev Enviroment is more for Server testing, but i need also the CLient and i look not often in the Log from the client. The server need a lot of more debuging as client. but it would be stable in future ;)

**Comment by TheMisterFish** [comment]
Since the error seems come from the chatSession I've added a mixin that checks if the player is a OfflinePlayer, if it is the OfflinePlayer does not get a chat session. 

https://www.mediafire.com/file/b9vx7wy1rminjui/offlineplayersreworked-1.1.0-test-V2.jar/file

**Comment by suerion** [comment]
Good day, no problem, yeah, i will test it if i had time,

On weekend i'm am on vacation, 

But next week i will try it.

Thanks for your good work and you had fixed all the bugs there. If i could help with fixing other things i will be here.

**Comment by TheMisterFish** [comment]
Closed by #39
