### ISSUE TITLE
[Feature] skip offline players when sleeping

### ISSUE THREAD

**Issue by Pino225** [TheMisterFish/Fabric_OfflinePlayersReworked#41]
**Is your feature request related to a problem? Please describe.**
I have a problem not being able to sleep when there are players who are afk

**Describe the solution you'd like**
so i suggest to add a feature to ignore afk players when other players want to sleep

**Additional context**
_Add any other context or screenshots about the feature request here._

**Versions**
- Minecraft: 1.21.1

**Comment by TheMisterFish** [comment]
Will look into this, nice feature idea :)

**Comment by TheMisterFish** [comment]
Feature is now available in 1.1.1, thank you for the suggestion 🙏
